name: Push workflow
on: [push]
jobs:
  code conformity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint code check
        run: npm run lint
      - name: Prettier code check
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --check ./src/**/*.js
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Unit Test
        run: npm run test
